#!/usr/bin/env python3
"""Generate and independently validate synthetic exports (requires dbfread==2.0.7).

Every package the Dart tests write must be one this script knows, and every
package it knows must have been written: a fixture that silently stops being
generated, or a new one nobody validates, fails here rather than passing.
"""
import argparse
import os
from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = 'artifacts/dbf-contract'
IMPORTER = 'artifacts/dbf-importer'
# Written by test/infrastructure/import_reports_test.dart without a source
# event, so only the schema and reciprocity checks apply to it.
RECIPROCITY_ONLY = 'artifacts/dbf'
IMPORTER_PACKAGES = ('mixed-long-first', 'mixed-short-first', 'rounds-1', 'rounds-32', 'quad',
                     'side-games', 'four-digit-opponents', 'double-blitz', 'blank-state',
                     'categories', 'double-byes-forfeits', 'round-robin-bye')
GENERATORS = ('test/infrastructure/rating_contract_test.dart',
              'test/infrastructure/dbf_importer_test.dart',
              'test/infrastructure/dbf_byte_contract_test.dart',
              'test/infrastructure/section_time_control_test.dart',
              'test/infrastructure/import_reports_test.dart')


def flutter_executable():
    # Windows ships flutter.bat, which subprocess cannot run by bare name.
    candidate = shutil.which('flutter')
    if not candidate:
        raise SystemExit('Flutter must be on PATH (or pass --validate-only)')
    return candidate


def package_issues(root):
    """Packages that were expected but not written, or written but not expected."""
    issues = []
    for folder in (CONTRACT, RECIPROCITY_ONLY, *(f'{IMPORTER}/{name}' for name in IMPORTER_PACKAGES)):
        if not (root / folder / 'TDEXPORT.DBF').is_file():
            issues.append(f'{folder} was not generated (run the Dart tests with MEOW_EXPORT_FIXTURES=1)')
    importer = root / IMPORTER
    if importer.is_dir():
        for extra in sorted({p.name for p in importer.iterdir() if p.is_dir()} - set(IMPORTER_PACKAGES)):
            issues.append(f'{IMPORTER}/{extra} is not validated; add it to IMPORTER_PACKAGES')
    return issues


def generate(root):
    # Stale packages from an earlier run must not stand in for ones a test
    # no longer writes.
    for folder in (CONTRACT, IMPORTER, RECIPROCITY_ONLY):
        shutil.rmtree(root / folder, ignore_errors=True)
    subprocess.run([flutter_executable(), 'test', '--concurrency=2', *GENERATORS], cwd=root,
                   env={**os.environ, 'MEOW_EXPORT_FIXTURES': '1'}, check=True)


def validate(root):
    issues = package_issues(root)
    if issues:
        raise SystemExit('FAIL:\n' + '\n'.join(issues))
    python = sys.executable
    for package in (CONTRACT, *(f'{IMPORTER}/{name}' for name in IMPORTER_PACKAGES)):
        subprocess.run([python, 'scripts/verify_dbf.py', package], cwd=root, check=True)
    subprocess.run([python, 'scripts/verify_dbf.py', RECIPROCITY_ONLY, '--reciprocity-only'], cwd=root, check=True)
    subprocess.run([python, 'scripts/test_dbf_validator.py', CONTRACT], cwd=root, check=True)
    subprocess.run([python, 'scripts/test_mock_uscf_importer.py'], cwd=root, check=True)
    subprocess.run([python, 'scripts/test_anonymize_boylston.py'], cwd=root, check=True)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--validate-only', action='store_true',
                        help='Use fixtures already generated by Flutter tests (CI).')
    args = parser.parse_args(argv)
    if not args.validate_only:
        generate(ROOT)
    validate(ROOT)


if __name__ == '__main__':
    main()
