#!/usr/bin/env python3
"""Generate and independently validate synthetic exports (requires dbfread==2.0.7)."""
import os
import argparse
from pathlib import Path
import subprocess
import sys

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--validate-only', action='store_true', help='Use fixtures already generated by Flutter tests (CI).')
args = parser.parse_args()
if not args.validate_only:
    subprocess.run(['flutter', 'test', '--concurrency=2',
                    'test/infrastructure/rating_contract_test.dart',
                    'test/infrastructure/dbf_importer_test.dart',
                    'test/infrastructure/section_time_control_test.dart'], cwd=root,
                   env={**os.environ, 'MEOW_EXPORT_FIXTURES': '1'}, check=True)
for package in ['artifacts/dbf-contract', *[f'artifacts/dbf-importer/{name}' for name in
                ('mixed-long-first', 'mixed-short-first', 'rounds-1', 'rounds-32', 'quad', 'side-games',
                 'four-digit-opponents', 'double-blitz', 'blank-state')]]:
    subprocess.run([sys.executable, 'scripts/verify_dbf.py', package], cwd=root, check=True)
subprocess.run([sys.executable, 'scripts/test_dbf_validator.py', 'artifacts/dbf-contract'], cwd=root, check=True)
subprocess.run([sys.executable, 'scripts/test_mock_uscf_importer.py'], cwd=root, check=True)
